### ISSUE TITLE
Error on bin/magento setup:di:compile

### ISSUE THREAD

**Issue by lorenzijo** [unbxd/Magento-2-Extension#1]
I get this error while running bin/magento setup:di:compile

Interception cache generation... 6/7 [========================>---]  85% 42 secs 333.0 MiBErrors during compilation:
	Unbxd\ProductFeed\Model\ResourceModel\IndexingQueue\Grid\Collection
		Incompatible argument type: Required type: string. Actual type: \Unbxd\ProductFeed\Model\ResourceModel\IndexingQueue\Grid\mainTable; File:
/var/www/html/app/code/Unbxd/ProductFeed/Model/ResourceModel/IndexingQueue/Grid/Collection.php

Total Errors Count: 1

In Log.php line 92:

  Error during compilation

To fix it please add string to mainTable in Model/ResourceModel/IndexingQueue/Grid/Collection.php as follow:
* @param string $mainTable

in line 47

**Comment by MageCloudTeam** [comment]
@lorenzijo 
resolved
please can you provide a more information about magento instance (verison, etc..) on which this issue was detected

**Comment by lorenzijo** [comment]
The magento version is 2.3.1 and this as well as the error about Unbxd_Analytics reported last week where found simply by running bin/magento setup:di:compile.

Thanks for fixing it
